# This is the corrected render.yaml file.

services:
  # ----------------------------------
  # 1. The Web Service for your Flask App
  # ----------------------------------
  - type: web
    name: projectpusher-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    # This is the CORRECT way to link an environment group
    envVars:
      - fromGroup: projectpusher-env # Make sure this is the exact name of your group

  # ----------------------------------
  # 2. The Background Worker for your worker.py
  # ----------------------------------
  - type: worker
    name: projectpusher-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    # Link the same group to the worker
    envVars:
      - fromGroup: projectpusher-env # Make sure this is the exact name of your group