# This is the final render.yaml file for free deployment.

services:
  # ----------------------------------
  # 1. The Web Service for your Flask App
  # ----------------------------------
  - type: web
    name: projectpusher-web
    env: python
    plan: free # <--- ADD THIS LINE to specify the free instance type
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - fromGroup: projectpusher-env 

  # ----------------------------------
  # 2. The Background Worker for your worker.py
  # ----------------------------------
  - type: worker
    name: projectpusher-worker
    env: python
    plan: free # <--- ADD THIS LINE to specify the free instance type
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    envVars:
      - fromGroup: projectpusher-env