# This is the final render.yaml for a single-service deployment on the free plan.

services:
  # We now only have ONE service. The worker logic is started by app.py.
  - type: web
    name: projectpusher # A simpler name for the combined service
    env: python
    plan: free 
    buildCommand: "pip install -r requirements.txt"
    # The start command is the same. Gunicorn starts app.py, which starts the worker.
    startCommand: "gunicorn app:app"
    envVars:
      - fromGroup: projectpusher-env 